---
title: "Using Frequency Tables with Multiple Variables"
---

Freq tables with many variables

Add this to the freqtables packagedown site.

Eventually add NHANES data to freq_tables package

https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.htm

```{r}
library(dplyr)
library(haven)
library(freqtables)
library(purrr)
```


```{r}
nhanes_17_18 <- read_xpt("https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.XPT")
```

Create a sample that we can add to R4Epi

```{r}
set.seed(123)
nhanes_17_18_50 <- nhanes_17_18 %>% 
  slice_sample(n = 50) %>% 
  select(SEQN, RIAGENDR, RIDAGEYR, RIDRETH1)
```

Make it easy to write out

```{r}
paste(paste0("~", names(nhanes_17_18_50)), collapse = ", ")
```

```{r}
nhanes_17_18_50 %>%
  rowwise() %>% 
  mutate(values = paste(c_across(), collapse = ", ")) %>% 
  ungroup() %>% 
  pull(values) %>% 
  paste0(", \n") %>% 
  cat()
```


```{r}
nhanes_17_18_50 <- tribble(
  ~SEQN, ~RIAGENDR, ~RIDAGEYR, ~RIDRETH1,
  96165, 2, 64, 5, 
  96213, 2, 17, 1, 
  102420, 2, 70, 1, 
  96688, 1, 58, 4, 
  95544, 1, 29, 3, 
  97073, 1, 44, 3, 
  98463, 2, 66, 3, 
  100448, 2, 16, 3, 
  96459, 2, 5, 5, 
  98809, 2, 1, 4, 
  102847, 2, 30, 3, 
  102911, 2, 55, 5, 
  96590, 2, 27, 1, 
  99872, 2, 31, 3, 
  96269, 2, 33, 1, 
  96682, 1, 10, 5, 
  95316, 1, 43, 3, 
  94257, 1, 11, 5, 
  98171, 2, 0, 3, 
  101491, 2, 12, 5, 
  102799, 2, 62, 5, 
  94749, 2, 13, 4, 
  100769, 2, 9, 5, 
  96706, 1, 40, 3, 
  96909, 1, 38, 3, 
  101691, 1, 3, 4, 
  97697, 1, 67, 4, 
  102060, 2, 80, 3, 
  93919, 2, 8, 3, 
  101859, 2, 64, 5, 
  99918, 2, 33, 5, 
  102482, 1, 36, 3, 
  95301, 2, 41, 5, 
  97939, 2, 1, 3, 
  97639, 1, 60, 3, 
  97791, 1, 11, 4, 
  96609, 2, 36, 4, 
  93996, 1, 3, 2, 
  102171, 2, 77, 5, 
  93743, 1, 61, 3, 
  102210, 1, 68, 4, 
  101093, 2, 63, 4, 
  100374, 2, 6, 3, 
  100986, 2, 50, 2, 
  96206, 1, 9, 3, 
  100444, 1, 0, 2, 
  102646, 2, 11, 4, 
  102268, 2, 10, 1, 
  99831, 1, 58, 4, 
  98314, 1, 25, 4
)
```

```{r}
nhanes_17_18_50 <- nhanes_17_18_50 %>%
  rename(gender = RIAGENDR, age = RIDAGEYR, race_eth = RIDRETH1) %>% 
  mutate(
    gender_f = factor(gender, 1:2, c("Male", "Female")),
    race_eth_f = factor(
      race_eth, 1:5,
      c("Mexican American", "Other Hispanic", "Non-Hispanic White", 
      "Non-Hispanic Black", "Other Race - Including Multi-Racial")
    )
  )
```

```{r}
nhanes_17_18_50 %>% 
  freq_table(gender_f)
```

```{r}
summary_stats <- map_df(
  .x = quos(gender_f, race_eth_f),
  .f = ~ freq_table(nhanes_17_18_50, !!.x)
)

summary_stats
```

```{r}
summary_stats %>% 
  freq_format("n (percent%)", digits = 1) %>% 
  select(var, cat, formatted_stats)
```



# Left off here. 

This works, but it would be nice if you didn't need to use `quos()` and `!!`. Maybe I can make a change to the freq_table function, or maybe I can can create a wrapper function. 








































